global using Concertable.Kernel;
global using Concertable.Kernel.ValueObjects;
global using Concertable.Contracts;
global using Concertable.Contracts.Enums;
global using Concertable.Messaging;
global using Concertable.DataAccess;
global using Concertable.Customer.Concert.Domain;
global using Concertable.Customer.Concert.Application.Interfaces;
global using Concertable.DataAccess.Infrastructure;
