<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerRepository>concertable/customer-migrations</ContainerRepository>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Concertable.Customer.DataAccess\Concertable.Customer.DataAccess.Infrastructure\Concertable.Customer.DataAccess.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Artist\Concertable.Customer.Artist.Infrastructure\Concertable.Customer.Artist.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Concert\Concertable.Customer.Concert.Infrastructure\Concertable.Customer.Concert.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Preference\Concertable.Customer.Preference.Infrastructure\Concertable.Customer.Preference.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Review\Concertable.Customer.Review.Infrastructure\Concertable.Customer.Review.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Ticket\Concertable.Customer.Ticket.Infrastructure\Concertable.Customer.Ticket.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\User\Concertable.Customer.User.Infrastructure\Concertable.Customer.User.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Venue\Concertable.Customer.Venue.Infrastructure\Concertable.Customer.Venue.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Concertable.Messaging.Infrastructure" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
